### PR TITLE
WMS ID: 11386

### PR DESCRIPTION
**Pull request by rcrajatchawla**
# WMS ID: 11386

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @rcrajatchawla,

In the lab section, please change the task to be shown from **Task 1**, to  Task 1. 

Do you mean to have the license txt in the language-oci-pipeland?

All files name should be in lowercase: 
image

Files should be stored in object storage. Please send livelabs-help-db_us@oracle.com an email with the files so that we can create the object storage for you. 

Please refer to the QA document to make sure you are following the right formatting. 
[QA (6).docx](https://github.com/oracle-livelabs/analytics-ai/files/11357237/QA.6.docx)

Thank you, 
Ramu

**Comment by rcrajatchawla** [comment]
Hi @ramumg, Thanks for the review.
These files were added by mistake. I have deleted the whole folder from the lab.

**Comment by rahul-tasker** [comment]
Hi @rcrajatchawla, I see that this workshop is in Self QA in WMS. Please perform thorough self-QA of the workshop using the Self QA Checklist in WMS and update the status to Self QA Complete to be able to review and approve this PR.

**Comment by klazarz** [comment]
@rcrajatchawla Please also make sure to lower-case all filenames.

**Comment by rcrajatchawla** [comment]
@klazarz Thanks for the feedback.
We have made the changes.

**Pull request merged**
