### PR TITLE
WMS ID #11397: Diversity and Inclusion workshop

### PR DESCRIPTION
**Pull request by jlklooste-oracle**
#11397

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@jlklooste-oracle - Please make these changes to the workshop.
- We recommend hosting files on object storage. Please email the files to livelabs-help-db_us@oracle.com mailbox and we will upload the files to object storage and share the PAR links with you. You can update the file reference in the labs to use the PAR links and delete the files from the repo.
image
- There are 2 occurrences of HTML (for example: <a href=...>) in your lab 2 Markdown. Please do not embed HTML in Markdown.
- In the labs modify "You may now proceed to the next lab." to bold proceed the next lab in the line.
- Could you update the freetier manifest.json Get Started link to -  https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md and Need help link to - https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md

**Comment by jlklooste-oracle** [comment]
Hi Anoosha, thank you for the review.
I've made all the changes you requested and committed to my GIT. 
Do I have to create a pull request again? Or can we keep using this one?
@anooshapilli

**Review by denisemyrick — APPROVED** [review]

**Review by denisemyrick — APPROVED** [review]

**Comment by denisemyrick** [comment]
Hi, you should be all set!

**Comment by jlklooste-oracle** [comment]
Thank you Anoosha,

When can I see the workshop on Live Labs please,

Regards,

Jeroen


From: denisemyrick ***@***.***>
Sent: Tuesday, May 16, 2023 5:03 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Jeroen Kloosterman ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] WMS ID #11397: Diversity and Inclusion workshop (PR #174)


Hi, you should be all set!

**Pull request merged**
