### PR TITLE
Updates to WMS ID's:  2060, 8241, 7001, 11230, 11133 (New DB action UI)

### PR DESCRIPTION
**Pull request by topformat**
Updates to WMS ID's:  2060, 8241, 7001, 11230, 11133 (New DB action UI)

All labs images and text updated to reflect new DB actions UI

### CODE REVIEW

**Comment by topformat** [comment]
Hi Carmen,  yes i seen there was a few that i have rectified as they were previously there already before my edits today.

Will i need to just do a new pull request now once they are changed on my side?

**Comment by carmenberdant1** [comment]
> Hi Carmen, yes i seen there was a few that i have rectified as they were previously there already before my edits today.
> 
> Will i need to just do a new pull request now once they are changed on my side?

Yes

**Comment by topformat** [comment]
Hi Carmen, sorry i am not too experienced in github, as this request is open and i cannot create another request as open, do i close this request first then open a separate request then?

**Comment by carmenberdant1** [comment]
> Hi Carmen, sorry i am not too experienced in github, as this request is open and i cannot create another request as open, do i close this request first then open a separate request then?

Hi, so you can make changes to this open PR, I'll dm you.

**Review by anacoman11 — APPROVED** [review]

**Review by carmenberdant1 — APPROVED** [review]

**Pull request merged**
