### PR TITLE
WMS ID:5741 New OCW23 HOL for data integration

### PR DESCRIPTION
**Pull request by davidallan**
# Add here your WMS ID
5741
# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by KillianLynch — COMMENTED** [review]
Hi @davidallan, would you update you development github URL in WMS to reflect the changes to the workshops folder 

https://theodoracristea.github.io/learning-library/data-management-library/oci-di/workshops/ocw23-livelabs/index.html

**Review by ZRTalke — DISMISSED** [review]
Hi @davidallan 

I'm reviewing the workshop and noticed a few items that need to be updated:

- Per LiveLabs guidelines, since you are submitting this pull request, you will need to be added to the team members section on the WMS page for your workshop before we will be able to accept it
- The introduction md file needs to be in it's own separate introduction folder
- As a follow up to Killian's remark, please inform us when the development url on the WMS page reflects the md files in the pull request so we can view the rendered page before accepting the pull request

Let me know if you have any questions. Thanks!

**Comment by davidallan** [comment]
Thanks @ZRTalke I've pushed the changes in the PR.

**Comment by ZRTalke** [comment]
Hi @davidallan 

Thanks for making those changes! 

For your development url on the WMS this needs to be a GitHub Pages github.io page not a github.com one. Please see this section of the livelabs instructions if you need help getting that
https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=3-labs-sync-github#Task7:SetupGitHubpagesforyourforktotestyourcontent

Your other changes look good including getting added to the workshop team on the WMS!

**Comment by davidallan** [comment]
Thanks Zachary I have updated WMS.

**Comment by anooshapilli** [comment]
@davidallan - Please update the introduction lab to look like this format - [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/sample-workshop/workshops/tenancy/)
- Lab 1 Task 2 Step 8, 12 - fix the bullet indentation with 4 spaces from the beginning of the line

**Comment by davidallan** [comment]
Updated the bullet points and also the introduction.

**Review by klazarz — APPROVED** [review]

**Pull request merged**
