### PR TITLE
WMS ID: 6181 - Updated for Langauge Service 2.0 

### PR DESCRIPTION
**Pull request by rajapratapk**
# WMS ID: 6181

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — CHANGES_REQUESTED** [review]
Due to Oracle Cloud World Support and company-wide freezes:
Please note that LiveLabs does not accept any PRs from October 10 until October 21.
Please see the postings in the slack channels.
Your PR will be set on hold until October 21.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all filenames are lower case 
2. All images should have descriptive alternative texts in the Markdown files for accessibility
3. You should not include any zip files in GitHub. Instead, send the zip file to livelabs-help-db_us@oracle.com, and we will upload the file and give you a PAR link
4. Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.

Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop. Can you ask someone listed as the workshop team (ankit.t.tyagi@oracle.com, rajat.c.chawla@oracle.com) to add you?
2. Make sure all filenames are lower case, including files under the "files" folder

**Comment by rajapratapk** [comment]
hi @arabellayao @anooshapilli I have checked again for upper case file names and ensured all the file names are in lower case. Also updated the links with PAR links you shared. Are there any file names I'm missing? please let me know.

I'm contacting the earlier authors to add me and Sahil into the list.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! From what I saw, the files below still have upper case letters. Could you please change them to lower case letters? Thanks!
Screen Shot 2022-10-25 at 10 47 45 AM
Screen Shot 2022-10-25 at 10 48 15 AM
Screen Shot 2022-10-25 at 10 48 29 AM

**Comment by rajapratapk** [comment]
hi @arabellayao @anooshapilli  file names are changed to lower case and I have been added to authors list. Please let me know if you need anything more.

**Comment by rajapratapk** [comment]
Hi Arabella,
Thank you. Below filenames are all fixed now. Please let us know if you anything more for approving the PR.

--
Pratap
Product Manager, Language Services
Oracle Health and AI Services


From: Arabella Yao ***@***.***>
Date: Tuesday, 25 October 2022 at 11:19 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Raja Pratap Kondamari ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] WMS ID: 6181 - Updated for Langauge Service 2.0 (PR #75)

@arabellayao requested changes on this pull request.

Hi! From what I saw, the files below still have upper case letters. Could you please change them to lower case letters? Thanks!
[Screen Shot 2022-10-25 at 10 47 45 AM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48001060/197845574-7b73b959-598f-491e-9d17-5aa9fd6c984c.png__;!!ACWV5N9M2RV99hQ!OSBFwlq4Cfni75765YXULSEtNZvhXNvHG1_cFS8fE4NiCxGw4Nik9gZ9SCzqhgeIn1dwfSGypvpaS9TfqTCPsEmlxsfIjkSoew$>
[Screen Shot 2022-10-25 at 10 48 15 AM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48001060/197845669-d99e4b01-ec59-47dd-a4eb-6f815b5774a7.png__;!!ACWV5N9M2RV99hQ!OSBFwlq4Cfni75765YXULSEtNZvhXNvHG1_cFS8fE4NiCxGw4Nik9gZ9SCzqhgeIn1dwfSGypvpaS9TfqTCPsEmlxse5hrNiAQ$>
[Screen Shot 2022-10-25 at 10 48 29 AM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48001060/197845727-1aa3349c-444b-4e0d-9623-b175b4cf6b5a.png__;!!ACWV5N9M2RV99hQ!OSBFwlq4Cfni75765YXULSEtNZvhXNvHG1_cFS8fE4NiCxGw4Nik9gZ9SCzqhgeIn1dwfSGypvpaS9TfqTCPsEmlxse001-xFw$>

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please change those filenames to lowercase. Thanks!
Screen Shot 2022-10-26 at 11 27 34 AM

**Comment by rajapratapk** [comment]
Hi Arabella,

This was due to sync issue with my GIT desktop. Corrected now.

--
Pratap
Product Manager, Language Services
Oracle Health and AI Services


From: Arabella Yao ***@***.***>
Date: Wednesday, 26 October 2022 at 11:58 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Raja Pratap Kondamari ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] WMS ID: 6181 - Updated for Langauge Service 2.0 (PR #75)

@arabellayao requested changes on this pull request.

Hi! Please change those filenames to lowercase. Thanks!
[Screen Shot 2022-10-26 at 11 27 34 AM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48001060/198106732-86804b87-722c-441f-977d-bc102aa6ed82.png__;!!ACWV5N9M2RV99hQ!Pk0QV6WLzmhfkvtHpY-u2aOoAxGgqAd4h7LtAdpCR37uCqtElMk_k8xMe__c1NtjChPzJ7tvXZ8iUYDGdwNlcDm_2pfNdLA8AQ$>

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
