### PR TITLE
WMS ID:660-fix the images title

### PR DESCRIPTION
**Pull request by JustinZou1**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by aberinnj** [comment]
Hi Justin, please confirm the checklist above and resolve the listed conflicts. I also saw that some files have uppercase letters

**Comment by JustinZou1** [comment]
Thanks, I have fix files have uppercase letters to lower letters.

**Comment by anooshapilli** [comment]
@JustinZou1 - Please make the requested changes and resolve the conflicting files in this PR.

**Comment by JustinZou1** [comment]
Hi team, I have fixed the conflicting at 20230331. Thanks

**Comment by anooshapilli** [comment]
@JustinZou1 - I would recommend testing the workshop against the Self-QA Checklist in WMS and make all the necessary changes to align with LiveLabs standards. Check all the boxes in the checklist and save it. Then update your workshop status to Quarterly QA Complete and save the status.

**Pull request merged**
