### PR TITLE
feat: updated manifest paths for my CloudWorld '23 sessions

### PR DESCRIPTION
**Pull request by jasperan**

### CODE REVIEW

**Comment by anooshapilli** [comment]
@jasperan - Could you share and update the PR with the WMS ID of the workshop?

**Comment by jasperan** [comment]
certainly @anooshapilli the changes are pertaining to two WMS IDS: 11228 and 11226

**Comment by anooshapilli** [comment]
@jasperan - Just following up on this PR.

**Comment by jasperan** [comment]
Yes @anooshapilli that reference will be removed, the index.html found in ocw23-tenancy will be the new production URL (I believe I did make this change in WMS as well).

**Review by anooshapilli — APPROVED** [review]

**Comment by anooshapilli** [comment]
@jasperan - I Updated the WMS brown button URL with the link - https://oracle-livelabs.github.io/analytics-ai/league-of-legends-data-extraction/ocw23-tenancy/index.html 
Could you create a new workshops folder under league-of-legends-data-extraction folder, move these two folders into that and create a new PR?
image

**Pull request merged**
