### PR TITLE
Latest self-QA changes

### PR DESCRIPTION
**Pull request by YanirShahak**
* Small structure updates
* Typos
* Formatting

### CODE REVIEW

**Comment by anooshapilli** [comment]
@YanirShahak - Please share the WMS ID of this workshop and resolve the conflicting files issue.

**Comment by YanirShahak** [comment]
WMSID: 11398
Working on merge conflicts

**Review by anooshapilli — COMMENTED** [review]
@YanirShahak - Please review this workshop using the Self QA Checklist and make necessary changes and then update the workshop status to Self QA Complete in WMS to review this PR.

**Review by bhenndricks — APPROVED** [review]

**Comment by YanirShahak** [comment]
@anooshapilli , done

**Review by anooshapilli — COMMENTED** [review]
@YanirShahak - Please make these changes to the workshop
- In the Introduction lab, Rename Estimated Time - to "Estimated Workshop Time:"
- Unbold Acknowledgments in all the labs and use this format for Acknowledgements - [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/sample-workshop/workshops/tenancy/?lab=provision#Acknowledgements)
- In Lab 1,2, 5, 6, 7, 8, 9, and 10 - rename Estimated Lab Time to Estimated Time and remove ~ in ETA in the labs
- In Lab 3, 4 - bullet the objectives and prerequisites instead of numbering
- In Lab 10, Rename Task 3 to Task 2

**Comment by YanirShahak** [comment]
@anooshapilli, done.

**Pull request merged**
