### PR TITLE
Add Document Understanding Lab

### PR DESCRIPTION
**Pull request by kddorazio**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by kddorazio** [comment]
Updated with lowercase file names

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Include the workshop’s WMS ID in the title of the PR
2. Make sure all filenames are lower case
3. Please follow the structure of LiveLabs workshop: the "workshops" folder should only contain the index.html and the manifest.json files. The individual lab folders should be directly under the "ai-document-understanding" folder.
Thanks!

**Comment by madhusudhanrao-ppm** [comment]
Image names should be all lowercase and self-descriptive, for example, create-compute-instance.png 

image

**Comment by arabellayao** [comment]
Hi! Please fix the following issues of your PR:

1. Include the workshop’s WMS ID in the title of the PR
2. Make sure all filenames are lower case and descriptive
3. Please follow the structure of LiveLabs workshop: the "workshops" folder should only contain the index.html and the manifest.json files. The individual lab folders should be directly under the "ai-document-understanding" folder.
4. Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.
Thanks!

**Comment by arabellayao** [comment]
Hi! I am closing this PR. Please fix the changes suggested above and create a new PR when you finish the changes. Thanks!

**Pull request closed without merging**
