### PR TITLE
WMS ID: 11423 Lab Updates

### PR DESCRIPTION
**Pull request by NagwangGyamtso**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by klazarz — CHANGES_REQUESTED** [review]
Hi @NagwangGyamtso please check that all filenames are lower case

**Comment by NagwangGyamtso** [comment]
> Hi @NagwangGyamtso please check that all filenames are lower case

Hi Kevin, I believe all filenames are lower case

**Review by ramonamagadan18 — CHANGES_REQUESTED** [review]
Hi @NagwangGyamtso please check if all filenames are lower case. In "manage-logical-table/images" you have 3 images with "LTS1" in name.

**Comment by NagwangGyamtso** [comment]
> Hi @NagwangGyamtso please check if all filenames are lower case. In "manage-logical-table/images" you have 3 images with "LTS1" in name.

Hi @ramonamagadan18 Good catch! I have updated the image names in both images folder and the .md files. Thank you!

**Review by klazarz — APPROVED** [review]

**Pull request merged**
