### PR TITLE
Publishing new livelab - Deploy an ODA Chatbot powered by Generative AI Agents using 23ai Vector DB: WMS ID 11764, also made changes to WMS ID 11617 

### PR DESCRIPTION
**Pull request by abhinavoracle**
WMS ID 11764, WMS ID 11617

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anacoman11 — DISMISSED** [review]
Hi @abhinavoracle, please change the name of these images: 

- atom/understandingDocument/images/Screenshot 2024-09-30 at 9.22.17 AM.png
- atom/provision/images/Screenshot 2024-09-30 at 9.22.17 AM.png

Please make these images to be clear, not blurred:

- generative-ai-agent-23ai/vb/images/vb_nav.png
- generative-ai-agent-23ai/vb/images/vb_import_type.png
- generative-ai-agent-23ai/vb/images/vb_import_config.png
- generative-ai-agent-23ai/vb/images/vb_create_wizard.png
- generative-ai-agent-23ai/sql/images/oda_service_console.png
- generative-ai-agent-23ai/sql/images/oda_create_wizard.png
- generative-ai-agent-23ai/sql/images/oda_active.png
- generative-ai-agent-23ai/sql/images/import_skill.png
- generative-ai-agent-23ai/sql/images/channel_nav.png
- generative-ai-agent-23ai/oda/images/oda_service_console.png
- generative-ai-agent-23ai/oda/images/oda_create_wizard.png
- generative-ai-agent-23ai/oda/images/oda_locate.png
- generative-ai-agent-23ai/oda/images/oda_create_wizard.png
- generative-ai-agent-23ai/oda/images/oda_active.png
- generative-ai-agent-23ai/oda/images/channel_nav.png
- generative-ai-agent-23ai/kb/images/oda_service_console.png
- generative-ai-agent-23ai/kb/images/oda_locate.png
- generative-ai-agent-23ai/kb/images/import_skill.png
- generative-ai-agent-23ai/kb/images/channel_nav.png
- generative-ai-agent-23ai/adb/images/oda_service_console.png
- generative-ai-agent-23ai/adb/images/oda_nav.png
- generative-ai-agent-23ai/adb/images/oda_locate.png
- generative-ai-agent-23ai/adb/images/oda_create_wizard.png
- generative-ai-agent-23ai/adb/images/oda_active.png
- generative-ai-agent-23ai/adb/images/launch_chat.png
- generative-ai-agent-23ai/adb/images/kb_create.png
- generative-ai-agent-23ai/adb/images/import_skill.png
- generative-ai-agent-23ai/adb/images/channel_nav.png


Please blur the private information from:

- generative-ai-agent-23ai/sql/images/vault-adb.png
- generative-ai-agent-23ai/sql/images/pvt_ip.png
- generative-ai-agent-23ai/sql/images/policy_details.png
- generative-ai-agent-23ai/sql/images/kb_create.png
- generative-ai-agent-23ai/sql/images/conn_string.png
- generative-ai-agent-23ai/oda/images/oda_active.png
- generative-ai-agent-23ai/kb/images/vault-adb.png
- generative-ai-agent-23ai/kb/images/pvt_ip.png
- generative-ai-agent-23ai/kb/images/policy_details.png
- generative-ai-agent-23ai/kb/images/oda_service_console.png
- generative-ai-agent-23ai/kb/images/oda_create_wizard.png
- generative-ai-agent-23ai/kb/images/locate_kb.png
- generative-ai-agent-23ai/kb/images/locate_agent.png
- generative-ai-agent-23ai/kb/images/conn_string.png
- generative-ai-agent-23ai/adb/images/vault-adb.png
- generative-ai-agent-23ai/adb/images/policy_details.png
- generative-ai-agent-23ai/adb/images/kb_create.png
- generative-ai-agent-23ai/adb/images/conn_string.png

Please resolve the branch out-of-date issue

**Comment by abhinavoracle** [comment]
@anacoman11 I've made requested changes. Please approve the PR. Need to publish it soon. Thank you

**Review by anacoman11 — COMMENTED** [review]
Hi @abhinavoracle, sent you a DM

**Comment by abhinavoracle** [comment]
@klazarz @anacoman11 I've redone all the images and am consistently using white blocks to block private information without any outline. Kindly please approve the PR. Let me know if anything else is needed from my end. Thank you!

**Review by klazarz — APPROVED** [review]

**Review by klazarz — APPROVED** [review]

**Pull request merged**
