### PR TITLE
Update: Common analytics labs

### PR DESCRIPTION
**Pull request by NagwangGyamtso**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by william-masdon-oracle** [comment]
please include the WMS ID in your PR

**Comment by NagwangGyamtso** [comment]
Hi William,

These updates are a part of the common analytics lab folder. They aren’t going to be published so it doesn’t have a WMS ID. They’re going to be pulled into other workshops which will have WMS IDs.

Thanks,
Nagwang

[Oracle]<http://www.oracle.com/>
Nagwang Gyamtso
Product Manager, Product Strategy, Analytics
LinkedIn: Linkedin.com/in/nagwanggyamtso/<https://www.linkedin.com/in/nagwanggyamtso/>
Mobile: +1.646.637.3997
Oracle Analytics

From: William Masdon ***@***.***>
Date: Monday, January 23, 2023 at 3:47 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Nagwang Gyamtso ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] Update: Common analytics labs (PR #98)

please include the WMS ID in your PR

**Comment by klazarz** [comment]
@NagwangGyamtso Common labs are OK. But what are the workshop folders and manifest related to?
Also, please make sure always to provide alternate text for images:
 
should be (or whatever alternative description fits)
 Create a dataset

**Comment by NagwangGyamtso** [comment]
Hi Kevin,

I forgot to mention that the workshop folders are for testing purpose only. Once the labs are finalized, I will remove them. I also just updated all the alternative text so it should be good now. Thanks!


[Oracle]<http://www.oracle.com/>
Nagwang Gyamtso
Product Manager, Product Strategy, Analytics
LinkedIn: Linkedin.com/in/nagwanggyamtso/<https://www.linkedin.com/in/nagwanggyamtso/>
Mobile: +1.646.637.3997
Oracle Analytics

From: Kevin Lazarz ***@***.***>
Date: Tuesday, January 24, 2023 at 3:12 AM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Nagwang Gyamtso ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] Update: Common analytics labs (PR #98)

@NagwangGyamtso<https://urldefense.com/v3/__https:/github.com/NagwangGyamtso__;!!ACWV5N9M2RV99hQ!M0pRUy5ptIQdGiqn4d_U_Gu_JZ9teVtQeeqjaq8hr_zwHDKE_P0BcEnYbYsKr5kNhgC6hWKi1lCHnCcKYmi-hk4lW7_TAw$> Common labs are OK. But what are the workshop folders and manifest related to?
Also, please make sure always to provide alternate text for images:
[X]<images/create-dataset.png>
should be (or whatever alternative description fits)
[Create a dataset]<images/create-dataset.png>

**Review by malcherm — APPROVED** [review]

**Pull request merged**
