### PR TITLE
Quarterly QA for all my labs

### PR DESCRIPTION
**Pull request by jasperan**
# WMS 11146, 11228, 11227, 11226

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @jasperan, it looks like you are trying to delete many files. Is this intentional? 

WMS ID:11226 points to leagueoflegends-optimizer as the production GitHub link, but you are trying to modify the files in the league-of-legends-data-extraction folder. Is this correct?

Please replace this link: https://raw.githubusercontent.com/oracle/learning-library/master/common/labs/cloud-login/cloud-login.md
for this link: https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md

Lastly, in the manifests, WMS ID: 11227 uses your email instead of livelabs-help-db_us@oracle.com. 

After clarifying this and the changes are done, we can approve this request. 

Please let me know if you have any questions, 
Ramu

**Comment by jasperan** [comment]
Hello @ramumg, yes it's intentional, but if you'd rather me keep the markdown files in this repository, I can add a commit and implement that, no problem.

I just do that to avoid redundancy since files (which take up repository storage and causes the git history to increase for new downloaders) are already contained in another repo which offloads this one, but let me know if this is something we want to overlook.

About the email in the manifests, I was under the impression that I should put my own email if I'm the HOL owner so that people can ask questions via email. Would you rather I put the livelabs-help email? I'm confused because the Quality Assurance review I did of the labs ask explicitly for my email

**Comment by jasperan** [comment]
I'll make the changes to the cloud-login links as well

**Review by ramumg — COMMENTED** [review]
Hi @jasperan, 
My apologies; the help email should be replaced with: livelabs-help-analytics_us@oracle.com since that is the stakeholder email in the WMS. 
We can delete those files to avoid redundancy; I wanted to double-check to ensure that's what you wanted.  

After the email is changed I will go ahead and approve and merge the PR. 

Thank you, 
Ramu

**Comment by jasperan** [comment]
Sounds good @ramumg let me make the changes to the files tomorrow and get this PR sorted out.

**Comment by jasperan** [comment]
@ramumg done

**Review by ramumg — APPROVED** [review]

**Pull request merged**
