### PR TITLE
WMS ID: 6861 Quarterly QA and updated UI images

### PR DESCRIPTION
**Pull request by topformat**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by topformat** [comment]
Hi Norman,

Ok just confirmed and checked the above checklist now thanks.

**Comment by anooshapilli** [comment]
@topformat - Please rename the images in these folders: heatwave, dbmds and analytics to have a descriptive title and make them all lower case to approve the PR.

**Review by bhenndricks — APPROVED** [review]

**Comment by anooshapilli** [comment]
@topformat -  Please rename all the images in heatwave, and analytics folders to have a descriptive title and make them all lowercase.

**Comment by topformat** [comment]
Hi Anoosha, i have now completed renaming all images to lowercase and also now descriptive

**Comment by topformat** [comment]
Do i need to create a new pull request separate as changes took a few days?

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
