### PR TITLE
WMS 11228 & 11226 & 11146 - Semi-final version

### PR DESCRIPTION
**Pull request by jasperan**
# Add here your WMS ID: 11228

# General requirements
1. Information in the workshop is adequate and updated - checked
2. Code is correct and working - checked
3. Links are correct - checked
4. Make sure you enter the help email link in your manifest.json - checked
5. Please make sure WMS URLs are updated as needed after your PR is approved - checked

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html -> Not using multiple versions but I've created all directories to increase portability.
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by jasperan** [comment]
# More info

I've also included WMS ID 11226 in this pull request. Both labs have been checked thoroughly.

# Add here your WMS ID: 11226

# General requirements
1. Information in the workshop is adequate and updated - checked
2. Code is correct and working - checked
3. Links are correct - checked
4. Make sure you enter the help email link in your manifest.json - checked
5. Please make sure WMS URLs are updated as needed after your PR is approved - checked


# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html -> Not using multiple versions but I've created all directories to increase portability.
- [x] Image references in markdown contain an alternate text

**Comment by jasperan** [comment]
# More info

Added WMS ID #11146 as the final LiveLabs workshop to upload in this pull request.

# Add here your WMS ID: 11146

# General requirements
1. Information in the workshop is adequate and updated - checked
2. Code is correct and working - checked
3. Links are correct - checked
4. Make sure you enter the help email link in your manifest.json - checked
5. Please make sure WMS URLs are updated as needed after your PR is approved - checked


# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html -> Not using multiple versions but I've created all directories to increase portability.
- [x] Image references in markdown contain an alternate text

**Comment by madhusudhanrao-ppm** [comment]
This branch is out-of-date with the base branch
Merge the latest changes from main into this branch.

**Comment by jasperan** [comment]
Done @madhusudhanrao-ppm

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
