### PR TITLE
fix the flink dashboard sample link

### PR DESCRIPTION
**Pull request by JustinZou1**
# Add here your WMS ID:11478

### CODE REVIEW

**Review by klazarz — APPROVED** [review]

**Comment by klazarz** [comment]
@JustinZou1 please fix the conflict

**Review by JustinZou — COMMENTED** [review]
would you show me what's conflict? Thanks

**Comment by hope-fisher** [comment]
@JustinZou this button will take you to existing conflicts. 
Screenshot 2023-10-24 at 3 45 20 PM

**Comment by JustinZou** [comment]
I don't have "resolve conflicts" button. It seams I don't write permission to fix the conflicts. 
image

**Comment by JustinZou1** [comment]
Hi, I have filxed the conflicts. Please check. Thanks

**Review by hope-fisher — APPROVED** [review]

**Pull request merged**
