### PR TITLE
[Korean] Premier League and Oracle: Expected Goals - Published-Public

### PR DESCRIPTION
**Pull request by jaesucjang**
# Add here your WMS ID
WMS ID: 11436
LiveLabs ID: 3727

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by jaesucjang — COMMENTED** [review]
I reviewed the corrected words

**Comment by jaesucjang** [comment]
Could you review the request ? thanks !

**Comment by anooshapilli** [comment]
@jaesucjang - In preparation for Oracle CloudWorld there is a GitHub freeze in place. We will only accept emergency PRs upon sending an email to livelabs-help-db_us@oracle.com including justification. If this is not urgent, please close this PR and create a new PR after the Oracle Cloudworld event.

**Comment by kamryn-v** [comment]
@jaesucjang - Closing this PR for now. Please create a new PR after the OCW event.

**Comment by jaesucjang** [comment]
Thanks for your help.

I will create the new one after oracle cloud world.

Best regards
Jason jang

2023년 8월 29일 (화) 오전 2:37, Kamryn Vinson ***@***.***>님이 작성:

**Pull request closed without merging**
