### PR TITLE
WMS11181-Galactic Exploration with OCI Vision

### PR DESCRIPTION
**Pull request by wprichard**
Updating procedures with testing edits.

### CODE REVIEW

**Review by klazarz — CHANGES_REQUESTED** [review]
@wprichard please make sure that all files are lower-case, for example, image files in z-data-files. Please remember to update the reference in markdown as well after renaming.

please note that 1:1 renaming in Git requires 'git mv' command!
If you do not want to use git mv, you can use a new name (lowercase).

**Comment by wprichard** [comment]
@klazarz Those files under z-data-files are not referenced in the markdown procedures. Those files are staged in the green button tenancy and are included in github in case the green button tenancy needs to be rebuilt at some point.

**Comment by wprichard** [comment]
File names have been updated to be all lower case

**Review by klazarz — DISMISSED** [review]

**Comment by anooshapilli** [comment]
@wprichard Could you resolve the conflicting files to approve the PR? Thanks!

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved 
Conflicting files
oci-artificial-intelligence/vision-space/0-introduction/0-introduction.md
oci-artificial-intelligence/vision-space/2-label-images/2-label-images.md
oci-artificial-intelligence/vision-space/2-label-images/images/click-create-dataset.png
oci-artificial-intelligence/vision-space/3-custom-model/3-custom-model.md
oci-artificial-intelligence/vision-space/3-custom-model/images/model-details.png
oci-artificial-intelligence/vision-space/4-explore-images/4-explore-images.md

**Pull request closed without merging**
