### PR TITLE
WMS ID:5741 New OCW23 HOL for data integration

### PR DESCRIPTION
**Pull request by davidallan**
# Add here your WMS ID
5741

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@davidallan - This workshop is in Quarterly QA status. Plese follow these steps to perform the QA of the workshop - [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=5-labs-qa-checks#Task3:SelfQA) and update your workshop status to Quarterly QA Complete. You can refer to this workshop folder structure to update your workshop folder structure - [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=4-labs-markdown-develop-content#Task1:Createyourlabsandworkshopcontent)

**Review by bhenndricks — APPROVED** [review]

**Review by anooshapilli — COMMENTED** [review]
@davidallan - Please make the changes to the workshop
- Add alternative text to images in the []
- In the manifest.json file, add Get Started lab after the introduction lab that points to cloud login instructions and Need Help lab at the end. [Sample](https://oracle-livelabs.github.io/common/sample-livelabs-templates/sample-workshop/workshops/tenancy/)
- We recommend only numbering with 1. 2. 3. format and not a. b. c. please bullet them or number them in the create-data-loader.md file

**Comment by davidallan** [comment]
Thanks @anooshapilli I have updated the image alternative text and the headings with a/b/c to bullets. For the getting started, at OCW23 we will be providing a tenancy and access, do we still need a Getting Started?

**Comment by davidallan** [comment]
@anooshapilli can you review the PR, its states At least 1 approving review is required by reviewers with write access.

**Comment by anooshapilli** [comment]
@davidallan - I still do not see all the requested changes. Please add the alternative text in the brackets, and get started lab in the manifest.json file. You can make these changes in your local and push them. They will be added to this PR. 
image

**Comment by anooshapilli** [comment]
@davidallan - Please make the requested changes by tomorrow. As the PR has been open for about two weeks now, we will close it and you can create a new one when you're ready. Thanks a lot for your understanding!

**Comment by anooshapilli** [comment]
@davidallan - Closing this PR. Please make these changes and create a new PR.
- Add alternative text to images within the []. You can view the example in Lab 4 Task 4 Step 2 [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=4-labs-markdown-develop-content#Task4:Linktoabsolutepathimages)
- In the manifest.json file, add Need Help lab at the end with this [LINK](https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md). You can view the sample [HERE](https://oracle-livelabs.github.io/common/sample-livelabs-templates/sample-workshop/workshops/tenancy/)
- We recommend only numbering with 1. 2. 3. format and not a. b. c. please bullet them or number them in the create-data-loader.md file

**Pull request closed without merging**
