### PR TITLE
WMS 11540: Lint checker completed for New Livelab

### PR DESCRIPTION
**Pull request by srinivas-srinivasarangachari**
# Add here your WMS ID

11540

# General requirements
1. Information in the workshop is adequate and updated - Yes
2. Code is correct and working - Yes
3. Links are correct - Yes
4. Make sure you enter the help email link in your manifest.json - Yes
5. Please make sure WMS URLs are updated as needed after your PR is approved - Yes

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ Yes] All filenames are lower case (including folders, images, files, etc.)
- [Yes ] Filenames are descriptive
- [ Yes] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ Yes] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ Yes] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by kaylien — DISMISSED** [review]

**Comment by kaylien** [comment]
@srinivas-srinivasarangachari please resolve conflicts before we merge. Thanks!

**Review by srinivas-srinivasarangachari — COMMENTED** [review]
Conflicts resolved

**Comment by kaylien** [comment]
@srinivas-srinivasarangachari unsure if the conflicts have been fully resolved, or maybe new ones popped up. Could you please resolve them again before we merge? Thanks!

**Comment by srinivas-srinivasarangachari** [comment]
@kaylien is it possible to have a quick call, I'm not sure about the conflicts, I do not seem to see any issues with the two highlighted files. Quick turnaround is much appreciated.

**Pull request merged**
