### PR TITLE
LWMS ID 5761: Updated for Quarterly QA and OCW 2023

### PR DESCRIPTION
**Pull request by plforacle**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @plforacle, 

Please rename the mysql/heatwave-intro folder to mysql-heatwave-intro. 

If you have notes inside your md files please use this syntax: 
image

**Comment by ramumg** [comment]
Hi @plforacle, 

please let me know if you need help making this change. After that we will be able to approve this PR. 

Thank you, 
Ramu

**Comment by plforacle** [comment]
Hi  @***@***.***>

I have made the following changes and updated GitHub.

LWMS ID 5761: @ramumg requested changes on this pull request. Please rename the mysql/heatwave-intro folder to mysql-heatwave-intro.

Thank you,
Perside Lafrance Foster | MySQL Principal Partners Solution Engineer
email: ***@***.******@***.***>
phone: 1.786.877.9063
Oracle  Florida

From: ramumg ***@***.***>
Sent: Thursday, April 27, 2023 11:05 AM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Perside Foster ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] LWMS ID 5761: Updated for Quarterly QA and OCW 2023 (PR #168)


Hi @plforacle<https://urldefense.com/v3/__https:/github.com/plforacle__;!!ACWV5N9M2RV99hQ!KBOF210Elj7M18RGhJ9_TaQqD7bqQnGnMyHlnMDKLsiwMBqAcKjtVFZf9ymKClZhxLi9aaUuhOzKhhMrMFojHekIaHYE$>,

please let me know if you need help making this change. After that we will be able to approve this PR.

Thank you,
Ramu

**Review by ramumg — COMMENTED** [review]
Hi @plforacle 

please make sure all the files are using - instead of _ : 
image
After that, I can go ahead and merge. 

Thank you, 
Ramu

**Comment by plforacle** [comment]
@ramumg

Done

LWMS ID 5761: @ramumg requested changes on this pull request. Please rename the mysql/heatwave-intro folder to mysql-heatwave-intro.

Perside Lafrance Foster | MySQL Principal Partners Solution Engineer
email: ***@***.******@***.***>
phone: 1.786.877.9063
Oracle  Florida

From: ramumg ***@***.***>
Sent: Thursday, April 27, 2023 12:50 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Perside Foster ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] LWMS ID 5761: Updated for Quarterly QA and OCW 2023 (PR #168)


@ramumg commented on this pull request.

Hi @plforacle<https://urldefense.com/v3/__https:/github.com/plforacle__;!!ACWV5N9M2RV99hQ!PWsWQqqyHsrFSavR3ed-5uF8O-NdsqAcuU6Wq56L2kcfFYJVVmzF4l0PLUa7rQfKT80IAircY7IwXhH4GfMIP3Y3FaY1$>

please make sure all the files are using - instead of _ :
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/84869754/234932379-a8af280a-f955-4681-a03e-ebbfc5a8e3f1.png__;!!ACWV5N9M2RV99hQ!PWsWQqqyHsrFSavR3ed-5uF8O-NdsqAcuU6Wq56L2kcfFYJVVmzF4l0PLUa7rQfKT80IAircY7IwXhH4GfMIP2t8hSPp$>
After that, I can go ahead and merge.

Thank you,
Ramu

**Review by ramumg — APPROVED** [review]

**Pull request merged**
