### PR TITLE
WMS ID 11317 + 11304: First draft of workshop

### PR DESCRIPTION
**Pull request by NagwangGyamtso**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! I saw two workshop folders in your PR. Do both of them belong to the workshop #11317? In WMS, please fill out the development GitHub URL field for this workshop. Thanks!

**Comment by NagwangGyamtso** [comment]
No, the provision-administer-oac belongs to WMS ID 11304. I will update the dev. link for the web semantic modeler in WMS. Thank you!


[Oracle]<http://www.oracle.com/>
Nagwang Gyamtso
Product Manager, Product Strategy, Analytics
LinkedIn: Linkedin.com/in/nagwanggyamtso/<https://www.linkedin.com/in/nagwanggyamtso/>
Mobile: +1.646.637.3997
Oracle Analytics

From: Arabella Yao ***@***.***>
Date: Wednesday, December 14, 2022 at 1:57 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Nagwang Gyamtso ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] WMS ID 11317: First draft of workshop (PR #91)

@arabellayao requested changes on this pull request.

Hi! I saw two workshop folders in your PR. Do both of them belong to the workshop #11317? In WMS, please fill out the development GitHub URL field for this workshop. Thanks!

**Comment by arabellayao** [comment]
Thank you! Please also update the Development GitHub URL for WMS ID 11304 in WMS, and add the WMS ID to the title of this PR.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Remove the need-help-freetier folder
2. Make sure you are using the correct "Get Started" and "Need Help" labs for different versions of the workshop. Refer to this folder for example: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/

**Comment by arabellayao** [comment]
Followed up with Nagwang on 12/20.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please correct the Get Started and Need Help labs for desktop and sandbox.

**Review by anooshapilli — APPROVED** [review]

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
