### PR TITLE
[Korean] Premier League and Oracle: Expected Goals

### PR DESCRIPTION
**Pull request by jaesucjang**
# 11436

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@jaesucjang - Could you share the WMS ID of this workshop. If this folder is not needed, please delete it. 
image

please rename these filenames to lower case
image

**Comment by jaesucjang** [comment]
Hi, Thanks for your support the WMS ID is : 11436 

and I just deleted the sample-workshop-jjs

**Comment by anooshapilli** [comment]
@jaesucjang - Please resolve the conflicting files issue.

**Comment by anooshapilli** [comment]
@jaesucjang - Please resolve the conflicting files issue to approve this PR.

**Comment by jaesucjang** [comment]
I think I soleved the conflict files issue, please review again, thanks~!

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
